[package]
name = "fedimint-nwc"
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0.75"
clap = { version = "3", features = ["derive", "env"] }
dotenv = "0.15.0"
multimint = { version = "0.3.6" }
# multimint = { path = "../multimint" }
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
